import { defineCollection, z, reference } from 'astro:content';

const authors = defineCollection({
  type: 'content',
  schema: z.object({
    name: z.string(),
    nameJa: z.string().optional(),
    slug: z.string().optional(),
    avatar: z.string().optional(),
    jobTitle: z.string().optional(),
    role: z.string().optional(),
    bio: z.string().max(300),
    bioLong: z.string().optional(),
    knowsAbout: z.array(z.string()).optional(),
    specialties: z.array(z.string()).optional(),
    sameAs: z.array(z.string()).optional(),
    twitter: z.string().optional(),
    linkedin: z.string().optional(),
    website: z.string().optional(),
    instagram: z.string().optional(),
    location: z.string().optional(),
    since: z.string().optional(),
    featured: z.boolean().optional(),
    order: z.number().optional(),
    lang: z.enum(['ja', 'es']).default('ja'),
    active: z.boolean().default(true),
  }),
});

const articles = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string().max(160),
    lead: z.string().max(300),
    pubDate: z.coerce.date(),
    updatedDate: z.coerce.date().optional(),
    pillar: z.enum(['travel', 'food', 'language', 'living', 'culture', 'football']),
    cluster: z.string(),
    intent: z.enum(['informational', 'commercial', 'transactional', 'navigational']),
    image: z.string().optional(),
    imageAlt: z.string().optional(),
    tags: z.array(z.string()),
    entities: z.array(z.string()),
    relatedArticles: z.array(z.string()).optional(),
    faq: z.array(z.object({ question: z.string(), answer: z.string() })).optional(),
    draft: z.boolean().default(false),
    lang: z.enum(['ja', 'es']).default('ja'),
    featured: z.boolean().default(false),
    author: reference('authors'),
    readingTime: z.number().optional(),
    schemaType: z.enum([
      'article',
      'recipe',
      'restaurant',
      'destination',
      'course',
      'sports',
    ]).default('article'),
    recipeData: z.object({
      cookTime: z.string().optional(),
      prepTime: z.string().optional(),
      recipeYield: z.string().optional(),
      recipeCategory: z.string().optional(),
    }).optional(),
    destinationData: z.object({
      locationName: z.string().optional(),
      country: z.string().default('ES'),
      attractions: z.array(z.string()).optional(),
    }).optional(),
    courseData: z.object({
      educationalLevel: z.string().optional(),
      provider: z.string().optional(),
    }).optional(),
    restaurantData: z.object({
      restaurantName: z.string().optional(),
      addressLocality: z.string().optional(),
      priceRange: z.string().optional(),
      cuisine: z.string().default('Spanish'),
    }).optional(),
  }),
});

const events = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string().max(160),
    date: z.coerce.date(),
    endDate: z.coerce.date().optional(),
    location: z.string(),
    price: z.string().optional(),
    lineUrl: z.string().optional(),
    image: z.string().optional(),
    tags: z.array(z.string()),
    draft: z.boolean().default(false),
  }),
});

const spainMap = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    description: z.string().max(160),
    lead: z.string(),
    province: z.string(),
    provinceJa: z.string(),
    region: z.string(),
    capital: z.string(),
    mapUrl: z.string().url(),
    linktreeUrl: z.string().url().default('https://linktr.ee/supeinclub'),
    mainDish: z.string(),
    mainDishJa: z.string(),
    bestSeason: z.string(),
    priceRange: z.string(),
    tags: z.array(z.string()),
    entities: z.array(z.string()),
    relatedTravel: z.string().optional(),
    relatedFood: z.array(z.string()).optional(),
    pubDate: z.coerce.date(),
    author: reference('authors'),
    lang: z.enum(['ja', 'es']).default('ja'),
    draft: z.boolean().default(false),
    neighborhoods: z.array(z.object({
      name: z.string(),
      nameJa: z.string(),
      vibe: z.string(),
      specialty: z.string(),
      bestTime: z.string(),
    })).optional(),
    specialties: z.array(z.object({
      name: z.string(),
      nameJa: z.string(),
      description: z.string(),
      category: z.enum(['前菜', 'メイン', 'デザート', 'ワイン', 'バル']),
    })).optional(),
    faq: z.array(z.object({
      question: z.string(),
      answer: z.string(),
    })),
  }),
});

export const collections = { articles, authors, events, 'spain-map': spainMap };
